TOP_100 = 'https://{{serverName}}/ws2.0/product/top100/{{regionCode}}/{{y}}/{{m}}/{{d}}?checklistSort=false&maxResults=100'
CHECKLIST_FEED_ON_DATE = 'https://{{serverName}}/ws2.0/product/lists/{{regionCode}}/{{y}}/{{m}}/{{d}}?maxResults=10'
RECENT_CHECKLIST_FEED = 'https://{{serverName}}/ws2.0/product/lists/{{regionCode}}?maxResults=15'
REGIONAL_STATS_ON_DATE = 'https://{{serverName}}/ws2.0/product/stats/{{regionCode}}/{{y}}/{{m}}/{{d}}'
VIEW_CHECKLIST = 'https://{{serverName}}/ws2.0/product/checklist/view/{{subId}}'
